spring.application.name=IJWL_JavaBackend
mybatis.mapper-locations=classpath*:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
spring.datasource.url=jdbc:mysql://localhost:3306/it_japanese_learning_system?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=${IJWL_TOKEN}
jwt.refresh-secret=${IJWL_REFRESH_TOKEN}